- name: Loops
  hosts: local
  connection: local
  tasks:
  - name: Print numbers from 1 to 5
    ansible.builtin.debug:
      msg: "Number is {{ item }}" #item name is a default word used in loops
    loop:
      - 1
      - 2
      - 3
      - 4
      - 5