- name: user creation errors
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: yes

  - name: print a message
    ansible.builtin.debug:
      msg: "{{ user_output }}